package com.definesys.dmportal.appstore.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.definesys.dmportal.appstore.bean.temp;

import com.definesys.dmportal.appstore.dao.tempDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tempDaoConfig;

    private final tempDao tempDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tempDaoConfig = daoConfigMap.get(tempDao.class).clone();
        tempDaoConfig.initIdentityScope(type);

        tempDao = new tempDao(tempDaoConfig, this);

        registerDao(temp.class, tempDao);
    }
    
    public void clear() {
        tempDaoConfig.clearIdentityScope();
    }

    public tempDao getTempDao() {
        return tempDao;
    }

}
